"""M3: add thesis_cards, kol_sources, kol_calls, long_term_memory, factor_weights tables

Revision ID: cd170ff359eb
Revises: 
Create Date: 2026-06-18 20:06:02.082997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd170ff359eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor_name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('previous_weight', sa.Float(), nullable=True),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('observation_period_active', sa.Boolean(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factor_weights_factor_name'), 'factor_weights', ['factor_name'], unique=False)
    op.create_table('kol_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kol_source_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('call_date', sa.DateTime(), nullable=False),
    sa.Column('call_price', sa.Float(), nullable=False),
    sa.Column('attribution_status', sa.String(length=20), nullable=False),
    sa.Column('pnl_30d', sa.Float(), nullable=True),
    sa.Column('pnl_60d', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_snippet', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kol_calls_kol_source_id'), 'kol_calls', ['kol_source_id'], unique=False)
    op.create_index(op.f('ix_kol_calls_ticker'), 'kol_calls', ['ticker'], unique=False)
    op.create_table('kol_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('long_term_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('original_date', sa.DateTime(), nullable=False),
    sa.Column('compressed_at', sa.DateTime(), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_term_memory_data_type'), 'long_term_memory', ['data_type'], unique=False)
    op.create_index(op.f('ix_long_term_memory_ticker'), 'long_term_memory', ['ticker'], unique=False)
    op.create_table('short_term_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_term_memory_ticker'), 'short_term_memory', ['ticker'], unique=False)
    op.create_table('thesis_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('entry_mode', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('key_assumptions', sa.JSON(), nullable=False),
    sa.Column('thesis_valid_status', sa.String(length=20), nullable=False),
    sa.Column('re_entry_flagged', sa.Boolean(), nullable=False),
    sa.Column('factor_snapshot', sa.JSON(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('actual_pnl_pct', sa.Float(), nullable=True),
    sa.Column('judgment_score', sa.Integer(), nullable=True),
    sa.Column('execution_score', sa.Integer(), nullable=True),
    sa.Column('close_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_cards_ticker'), 'thesis_cards', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_cards_ticker'), table_name='thesis_cards')
    op.drop_table('thesis_cards')
    op.drop_index(op.f('ix_short_term_memory_ticker'), table_name='short_term_memory')
    op.drop_table('short_term_memory')
    op.drop_index(op.f('ix_long_term_memory_ticker'), table_name='long_term_memory')
    op.drop_index(op.f('ix_long_term_memory_data_type'), table_name='long_term_memory')
    op.drop_table('long_term_memory')
    op.drop_table('kol_sources')
    op.drop_index(op.f('ix_kol_calls_ticker'), table_name='kol_calls')
    op.drop_index(op.f('ix_kol_calls_kol_source_id'), table_name='kol_calls')
    op.drop_table('kol_calls')
    op.drop_index(op.f('ix_factor_weights_factor_name'), table_name='factor_weights')
    op.drop_table('factor_weights')
    # ### end Alembic commands ###
